---
- hosts: all
  become: true
  
  pre_tasks:
    - name: update the apt cache if a must
      apt:
       update_cache: yes
       cache_valid_time: 3600

  tasks:
    - name: Install Git package
      apt:
       name: git
       state: latest
       update_cache: yes

    - name: Install dependancy.
      apt:
       name:
         - apt-transport-https
         - ca-certificates
         - curl
         - gnupg-agent
         - software-properties-common
         - python3-pip
         - virtualenv
         - python3-setuptools
       state: latest
       update_cache: yes
         
    - name: add GPG keys
      apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present

    - name: add docker repository to apt
      apt_repository:
       repo: deb https://download.docker.com/linux/ubuntu bionic stable
       state: present

    - name: install docker
      apt:
       name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
       state: latest
       update_cache: yes
    
    - name: Make sure docker is running and will run on booting
      service:
        name: docker
        state: started
        enabled: yes

    # - name: Install docker-compose
    #   get_url:
    #     url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    #     dest: /usr/local/bin/docker-compose
    #     mode: '755'

    - name: Install docker compose python package.
      ansible.builtin.pip:
        name: docker-compose

    - name: Install docker module for python
      pip:
       name: docker

    - name: Import public key
      apt_key:
        url: 'https://www.mongodb.org/static/pgp/server-6.0.asc'
        state: present

    - name: Add repository
      apt_repository:
        filename: '/etc/apt/sources.list.d/mongodb-org-6.0.list'
        repo: 'deb https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/6.0 multiverse'
        state: present
        update_cache: yes

    - name: Install mongoDB
      apt: 
        name: mongodb-org
        state: present
        update_cache: yes 

    - name: Ensure mongodb is running and and enabled to start automatically on reboots
      service: 
        name: mongod 
        enabled: yes
        state: started   

    - name: git clone the yolo repository
      ansible.builtin.git:
         repo: https://github.com/AlbertineN/yolo.git
         dest: /usr/local/src/yolo
         version: master

    - name: Run docker-compose 
      docker_compose:
       project_src: /usr/local/src/yolo
       state: present           
           
           

      
         